### ISSUE TITLE
In the URL, District_Code value is missing

### ISSUE THREAD

**Issue by madhupkumar** [abhisheksinha08/HaryanaSoilNutrientDataExtracter#1]
In the generated csv file, for all URLs, the District_Code is missing. So if we use the URL, the website responds with an error about no district code.

e.g. the first row's URL

http://soilhealth.dac.gov.in/PublicReports/NutrientsStatusPartial?State_Code=6&District_Code=&Block_Code=447

should be

http://soilhealth.dac.gov.in/PublicReports/NutrientsStatusPartial?State_Code=6&District_Code=70&Block_Code=447

**Comment by madhupkumar** [comment]
This can be fixed at Line 59  where 't' is missing   "DistricId" should be "DistrictId"

**Comment by abhisheksinha08** [comment]
Issue Resolved in commit 296f409f526d73622650e96bc4c83ed254bfa2b0
